const $=id=>document.getElementById(id);let ws,lastState,lastImage;const video=$('video'),overlay=$('overlay'),vctx=video.getContext('2d'),octx=overlay.getContext('2d');
const defaults={HIDs:true,T:false,trails:true,hands:false,proximity:false,events:false,pending:true,stitches:false,yolo:false,diagnostics:false};let toggles={...defaults};
function draw(){if(!lastImage||!lastState)return;const iw=lastState.source_width||lastImage.width,ih=lastState.source_height||lastImage.height;video.width=iw;video.height=ih;overlay.width=iw;overlay.height=ih;vctx.drawImage(lastImage,0,0,iw,ih);octx.clearRect(0,0,iw,ih);const colors=['#61d4ff','#ffad5c','#d58cff','#7ee787','#ff7190','#f2e66b'];const hid=t=>t.hid||t.display_hid;for(const t of lastState.tracks||[]){const x=t.x??t.center_x,y=t.y??t.center_y;if(x==null)continue;const c=colors[((hid(t)||t.track_id||0)-1)%colors.length];octx.strokeStyle=c;octx.fillStyle=c;octx.lineWidth=2;octx.beginPath();octx.arc(x,y,7,0,Math.PI*2);octx.stroke();let label='';if(t.hid&&toggles.HIDs)label+=`HID${t.hid} `;if(toggles.T)label+=`T${t.track_id}`;if(label){octx.font='bold 14px system-ui';octx.fillText(label,x+9,y-8)}}if(toggles.hands){for(const [side,p] of Object.entries(lastState.hands||{})){if(!p)continue;const x=p.x??p[0],y=p.y??p[1];if(x==null)continue;octx.fillStyle=side==='LEFT'?'#75a7ff':'#ff8a9b';octx.beginPath();octx.arc(x,y,8,0,Math.PI*2);octx.fill();octx.fillText(side,x+10,y)}}drawExtras()}
function drawExtras(){if(toggles.proximity){for(const p of Object.values(lastState.proximity||{})){octx.fillStyle='rgba(80,160,255,.10)';octx.strokeStyle='rgba(80,160,255,.45)';octx.beginPath();octx.arc(p.x,p.y,p.possible_radius,0,Math.PI*2);octx.fill();octx.stroke();octx.strokeStyle='rgba(255,220,80,.55)';octx.beginPath();octx.arc(p.x,p.y,p.very_near_radius,0,Math.PI*2);octx.stroke()}}
if(toggles.pending){for(const p of lastState.pending||[]){const w=(lastState.hands||{})[p.wrist_side];const x=w?.x??lastState.source_width/2,y=w?.y??30;octx.fillStyle='#ffbf69';octx.fillRect(x-5,y-18,115,22);octx.fillStyle='#111';octx.font='bold 12px system-ui';octx.fillText(`${p.wrist_side||'AMB'} HID${p.hid||'?'} pending`,x,y-3)}}
if(toggles.stitches){for(const b of lastState.bridges_recent||[]){const a=(lastState.tracks||[]).find(t=>t.track_id===b.source_track_id),z=(lastState.tracks||[]).find(t=>t.track_id===b.target_track_id);if(a&&z){octx.strokeStyle='#ffbf69';octx.setLineDash([7,5]);octx.beginPath();octx.moveTo(a.x,a.y);octx.lineTo(z.x,z.y);octx.stroke();octx.setLineDash([]);octx.fillText(`HAND · ${b.hand}`,z.x,z.y+20)}}}}
function setPreset(name){toggles=name==='clean'?{...defaults}:name==='research'?{HIDs:true,T:true,trails:true,hands:true,proximity:true,events:true,pending:true,stitches:true,yolo:false,diagnostics:true}:{HIDs:false,T:true,trails:true,hands:true,proximity:false,events:false,pending:false,stitches:false,yolo:true,diagnostics:false};renderToggles();draw()}
function renderToggles(){const box=$('toggles');box.innerHTML='';Object.keys(toggles).forEach(k=>{const l=document.createElement('label');l.className='toggle';l.innerHTML=`<input type="checkbox" ${toggles[k]?'checked':''}> ${k}`;l.firstChild.onchange=e=>{toggles[k]=e.target.checked;draw()};box.appendChild(l)})}
function post(path,body){return fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined})}
$('start').onclick=()=>{const cfg={source:$('source').value,camera_index:+$('camera').value,video_path:$('path').value,model:$('model').value,device:$('device').value,record:$('record').checked};post('/api/start',cfg);connect();$('status').textContent='starting'};$('pause').onclick=()=>post('/api/control/pause');$('restart').onclick=()=>post('/api/control/restart');$('stop').onclick=()=>post('/api/control/stop');document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>setPreset(b.dataset.preset));
function connect(){if(ws)ws.close();ws=new WebSocket(`ws://${location.host}/ws`);ws.binaryType='arraybuffer';ws.onmessage=e=>{if(typeof e.data==='string'){lastState=JSON.parse(e.data);if(lastState.error){$('status').textContent=lastState.error;return}updatePanel()}else{const blob=new Blob([e.data],{type:'image/jpeg'});const img=new Image();img.onload=()=>{lastImage=img;draw()};img.src=URL.createObjectURL(blob)}};ws.onclose=()=>$('status').textContent='disconnected'}
function updatePanel(){const s=lastState,c=s.counts||{},r=s.runtime||{};$('status').textContent=`frame ${s.frame_id} · ${r.device||'unknown'}`;$('diag').innerHTML=[['source',s.source_width+'×'+s.source_height],['source FPS',(s.source_fps||0).toFixed(1)],['processing FPS',(s.processing_fps||0).toFixed(1)],['latency',(s.latency_ms||0).toFixed(1)+' ms'],['device',r.device||'not initialized'],['model',r.model||''],['CUDA',r.cuda?'yes':'no'],['visible tracks',c.visible_tracks||0],['display HIDs',c.display_hids||0],['pending',c.pending||0]].map(x=>`<dt>${x[0]}</dt><dd>${x[1]}</dd>`).join('');$('pending').textContent=(s.pending||[]).map(p=>`${p.hand||'AMB'}\nHID${p.hid||'?'} / T${p.track_id||'?'} · ${p.age_seconds||0}s`).join('\n')||'empty';const es=$('events');es.innerHTML=(s.events_recent||[]).slice(-50).reverse().map((e,i)=>`<div class="event" data-i="${i}">${e.frame??''} T${e.track_id??''} ${e.event_type??''} ${e.hand??''} ${e.association??''}</div>`).join('');es.querySelectorAll('.event').forEach((el,i)=>el.onclick=()=>{$('evidence').textContent=JSON.stringify((s.events_recent||[]).slice(-50).reverse()[i],null,2)});draw()}
renderToggles();
